sudo: required

services:
  - docker

before_install:
  - docker build -t hello-docker .
  - docker run -d -p 80:80 hello-docker

script:
  - curl --retry 2 --retry-delay 5 -v http://localhost/hello/docker

after_script:
  - docker rm -f hello-docker
