language: python
sudo: required

services:
  - docker

before_install:
  - docker build -t hello-docker .
  - docker run -d -p 5000:5000 hello-docker

script:
  - sleep 1
  - curl -v http://localhost:5000/hello/docker

after_script:
  - docker rm -f hello-docker
