language: python
sudo: required

services:
  - docker

before_install:
  - docker version
  - docker build -t flask .
  - docker run -d -p 5000:5000 --name flask flask

script:
  - sleep 0.2
  - curl http://localhost:5000/docker

after_script:
  - docker rm -f flask
