sudo: required

services:
  - docker

before_install:
  - docker build -t hello-docker .
  - docker run -d -P hello-docker

script:
  # - curl --retry 2 --retry-delay 5 -v http://localhost:5000/hello/docker
  - sleep 5
  - curl -v http://localhost:5000/hello/docker

after_script:
  - docker rm -f hello-docker
