language: python
sudo: required

services:
  - docker

before_install:
  - service docker start
  - docker version
  - docker build -t hello .
  - docker run -d -p 5000:5000 --name hello hello

script:
  - sleep 0.5
  - curl http://localhost:5000/docker

after_script:
  - docker rm -f hello
