language: python
sudo: required

services:
  - docker

before_install:
  - docker version
  - docker build -t ptdorf/flask .
  - docker run -d -p 5000:5000 --name flask ptdorf/flask

script:
  - sleep 0.2
  - curl http://localhost:5000/docker

after_script:
  - docker rm -f flask

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ptdorf/flask;
    fi
